language: android
jdk: oraclejdk8

android:
  components:
  #The versions that our project structures uses
    - build-tools-27.0.3
    - android-28
  licenses:
  #The first two lines are because, linux in travis sometimes skips it
    - "android-sdk-license-.+"
    - "google-gdk-license-.+"
    - yes | sdkmanager "build-tools;27.0.3"
    - yes | sdkmanager "platforms;android-28"

before_script:
#Giving permision
    - chmod +x gradlew
    
script:
#clean build cannot be used, assemblerelease forces the google extension
  - "./gradlew assemblerelease"
  - "./gradlew clean"
