language: android
sudo: required #Added for license issues
jdk: oraclejdk8

android:
  components:
  #The versions that our project structures uses
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - extra-android-support
    - addon-google_apis-google-27 # google play services
    - addon-google_apis-google-28 # google play services

  licenses:
  #The first two lines are forcing extra licenses
    - "android-sdk-license-.+"
    - "google-gdk-license-.+"
    - yes | sdkmanager "build-tools;27.0.3"
    - yes | sdkmanager "platforms;android-27"
    - yes | sdkmanager "platforms;android-28"

before_script:
#Giving permision
    - chmod +x gradlew
    - ./gradlew dependencies || true

script:
    - "./gradlew clean"
    - "./gradlew generatePlayDebugSources"
    - "./gradlew compilePlayDebugSources"
    - "./gradlew mockableAndroidJar"
    - "./gradlew compilePlayDebugUnitTestSources"
